version: "3.7"
services:
  chaperoo-client:
    image: kuddin1234/chaperoo-client
    build: .
    ports:
      - target: 80
        published: 80
    depends_on:
      - chaperoo-service    
  chaperoo-service: 
    image: kuddin1234/chaperoo-service
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on: 
      - chaperoo-db
  chaperoo-db:
    image: kuddin1234/chaperoo-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
